# Generated by Django 4.2.1 on 2023-11-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_blockchainrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchainrecord',
            name='current_hash',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='blockchainrecord',
            name='previous_hash',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
