# Generated by Django 4.2.1 on 2023-11-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_blockchainrecord_current_hash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockchainrecord',
            name='current_hash',
        ),
        migrations.RemoveField(
            model_name='blockchainrecord',
            name='previous_hash',
        ),
        migrations.AddField(
            model_name='blockchainrecord',
            name='block_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
