# Generated by Django 4.2.1 on 2023-11-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_blockchainrecord_current_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchainrecord',
            name='prev_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
